# Generated by Django 2.2.13 on 2021-08-13 11:15

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/photos/%Y/%m/%d', validators=[photos.models.Photo.validate_image_size]),
        ),
    ]
