# Generated by Django 2.2.13 on 2021-08-13 14:49

from django.db import migrations
import photos.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210813_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/photos/%Y/%m/%d', validators=[photos.models.Photo.validate_image_size]),
        ),
    ]
